export interface BreedInfo {
  name: string;
  slug: string;
  group: string;
  description: string;
  avgLitterSize: string;
  typicalPriceRange: string;
  weight: string;
  lifespan: string;
  temperament: string[];
}

export const BREEDS: BreedInfo[] = [
  { name: "Labrador Retriever", slug: "labrador-retriever", group: "Sporting", description: "America's most popular dog breed. Friendly, active, and outgoing, Labs are ideal family companions and excel as service, therapy, and detection dogs.", avgLitterSize: "6–8", typicalPriceRange: "$1,000–$2,500", weight: "55–80 lbs", lifespan: "11–13 years", temperament: ["Friendly", "Active", "Outgoing"] },
  { name: "French Bulldog", slug: "french-bulldog", group: "Non-Sporting", description: "Compact, muscular, and full of personality. Frenchies are adaptable city dogs with a playful, alert demeanor and minimal exercise needs.", avgLitterSize: "3–4", typicalPriceRange: "$2,500–$5,000", weight: "16–28 lbs", lifespan: "10–12 years", temperament: ["Adaptable", "Playful", "Alert"] },
  { name: "Golden Retriever", slug: "golden-retriever", group: "Sporting", description: "Intelligent, friendly, and devoted. Goldens are one of the most popular family dogs, known for their patience with children and eagerness to please.", avgLitterSize: "6–8", typicalPriceRange: "$1,500–$3,500", weight: "55–75 lbs", lifespan: "10–12 years", temperament: ["Intelligent", "Friendly", "Devoted"] },
  { name: "German Shepherd", slug: "german-shepherd", group: "Herding", description: "Confident, courageous, and smart. German Shepherds are versatile working dogs used in police, military, and search-and-rescue roles worldwide.", avgLitterSize: "6–8", typicalPriceRange: "$1,500–$3,000", weight: "50–90 lbs", lifespan: "7–10 years", temperament: ["Confident", "Courageous", "Smart"] },
  { name: "Poodle", slug: "poodle", group: "Non-Sporting", description: "Exceptionally intelligent and elegant. Poodles come in three sizes and are hypoallergenic, making them popular for families with allergies.", avgLitterSize: "4–6", typicalPriceRange: "$1,500–$3,000", weight: "40–70 lbs (Standard)", lifespan: "10–18 years", temperament: ["Intelligent", "Active", "Proud"] },
  { name: "Bulldog", slug: "bulldog", group: "Non-Sporting", description: "Calm, courageous, and friendly. The Bulldog's distinctive wrinkled face and sturdy build make it one of the most recognizable breeds.", avgLitterSize: "3–4", typicalPriceRange: "$2,000–$4,000", weight: "40–50 lbs", lifespan: "8–10 years", temperament: ["Calm", "Courageous", "Friendly"] },
  { name: "Rottweiler", slug: "rottweiler", group: "Working", description: "Loyal, loving, and confident guardians. Rottweilers are powerful working dogs that bond closely with their families.", avgLitterSize: "6–10", typicalPriceRange: "$1,500–$3,000", weight: "80–135 lbs", lifespan: "9–10 years", temperament: ["Loyal", "Loving", "Confident"] },
  { name: "Beagle", slug: "beagle", group: "Hound", description: "Merry, friendly, and curious. Beagles are excellent family dogs with a keen sense of smell and a gentle disposition.", avgLitterSize: "4–6", typicalPriceRange: "$800–$1,500", weight: "20–30 lbs", lifespan: "10–15 years", temperament: ["Merry", "Friendly", "Curious"] },
  { name: "Dachshund", slug: "dachshund", group: "Hound", description: "Clever, lively, and courageous. These iconic long-bodied dogs were originally bred to hunt badgers and have bold personalities.", avgLitterSize: "4–6", typicalPriceRange: "$1,000–$2,500", weight: "16–32 lbs", lifespan: "12–16 years", temperament: ["Clever", "Lively", "Courageous"] },
  { name: "German Shorthaired Pointer", slug: "german-shorthaired-pointer", group: "Sporting", description: "Versatile, enthusiastic, and willing to please. GSPs are premier sporting dogs that excel in the field and make energetic family companions.", avgLitterSize: "8–12", typicalPriceRange: "$1,000–$2,500", weight: "45–70 lbs", lifespan: "12–14 years", temperament: ["Friendly", "Smart", "Willing to Please"] },
  { name: "Pembroke Welsh Corgi", slug: "pembroke-welsh-corgi", group: "Herding", description: "Affectionate, smart, and alert. Corgis are surprisingly athletic herding dogs in a compact package, known for their fox-like faces.", avgLitterSize: "5–7", typicalPriceRange: "$1,500–$3,000", weight: "25–30 lbs", lifespan: "12–13 years", temperament: ["Affectionate", "Smart", "Alert"] },
  { name: "Australian Shepherd", slug: "australian-shepherd", group: "Herding", description: "Smart, work-oriented, and exuberant. Aussies are highly trainable herding dogs that thrive with active families.", avgLitterSize: "6–7", typicalPriceRange: "$1,000–$2,500", weight: "40–65 lbs", lifespan: "12–15 years", temperament: ["Smart", "Work-Oriented", "Exuberant"] },
  { name: "Yorkshire Terrier", slug: "yorkshire-terrier", group: "Toy", description: "Feisty, affectionate, and sprightly. Yorkies are tiny but bold terriers with luxurious silky coats.", avgLitterSize: "3–5", typicalPriceRange: "$1,500–$3,000", weight: "4–7 lbs", lifespan: "11–15 years", temperament: ["Affectionate", "Sprightly", "Tomboyish"] },
  { name: "Cavalier King Charles Spaniel", slug: "cavalier-king-charles-spaniel", group: "Toy", description: "Gentle, graceful, and affectionate. Cavaliers combine the athleticism of a sporting spaniel with the gentle nature of a toy breed.", avgLitterSize: "3–5", typicalPriceRange: "$2,000–$3,500", weight: "13–18 lbs", lifespan: "12–15 years", temperament: ["Affectionate", "Gentle", "Graceful"] },
  { name: "Doberman Pinscher", slug: "doberman-pinscher", group: "Working", description: "Loyal, fearless, and alert. Dobermans are elegant yet powerful dogs known for their intelligence and devotion to family.", avgLitterSize: "6–8", typicalPriceRange: "$1,500–$3,000", weight: "60–100 lbs", lifespan: "10–12 years", temperament: ["Loyal", "Fearless", "Alert"] },
  { name: "Boxer", slug: "boxer", group: "Working", description: "Fun-loving, bright, and active. Boxers are upbeat, playful dogs that are patient and protective with children.", avgLitterSize: "6–8", typicalPriceRange: "$1,000–$2,500", weight: "50–80 lbs", lifespan: "10–12 years", temperament: ["Fun-Loving", "Bright", "Active"] },
  { name: "Miniature Schnauzer", slug: "miniature-schnauzer", group: "Terrier", description: "Friendly, smart, and obedient. Mini Schnauzers are adaptable dogs that do equally well in the city or country.", avgLitterSize: "4–6", typicalPriceRange: "$1,000–$2,500", weight: "11–20 lbs", lifespan: "12–15 years", temperament: ["Friendly", "Smart", "Obedient"] },
  { name: "Cane Corso", slug: "cane-corso", group: "Working", description: "Intelligent, majestic, and protective. This Italian mastiff is a formidable guardian that is also affectionate with its family.", avgLitterSize: "6–8", typicalPriceRange: "$2,000–$4,000", weight: "88–110 lbs", lifespan: "9–12 years", temperament: ["Intelligent", "Majestic", "Protective"] },
  { name: "Great Dane", slug: "great-dane", group: "Working", description: "Friendly, patient, and dependable. Despite their towering size, Great Danes are gentle giants known for their sweet temperament.", avgLitterSize: "8–10", typicalPriceRange: "$1,500–$3,000", weight: "110–175 lbs", lifespan: "7–10 years", temperament: ["Friendly", "Patient", "Dependable"] },
  { name: "Shih Tzu", slug: "shih-tzu", group: "Toy", description: "Affectionate, happy, and outgoing. Shih Tzus are charming little dogs bred as royal companions in ancient China.", avgLitterSize: "3–5", typicalPriceRange: "$1,000–$2,500", weight: "9–16 lbs", lifespan: "10–18 years", temperament: ["Affectionate", "Happy", "Outgoing"] },
  { name: "Siberian Husky", slug: "siberian-husky", group: "Working", description: "Loyal, outgoing, and mischievous. Huskies are stunning sled dogs that are pack-oriented and love outdoor adventures.", avgLitterSize: "4–6", typicalPriceRange: "$1,000–$2,500", weight: "35–60 lbs", lifespan: "12–14 years", temperament: ["Loyal", "Outgoing", "Mischievous"] },
  { name: "Bernese Mountain Dog", slug: "bernese-mountain-dog", group: "Working", description: "Good-natured, calm, and strong. Berners are versatile Swiss farm dogs known for their striking tri-color coat and gentle disposition.", avgLitterSize: "6–8", typicalPriceRange: "$2,000–$4,000", weight: "70–115 lbs", lifespan: "7–10 years", temperament: ["Good-Natured", "Calm", "Strong"] },
  { name: "Pomeranian", slug: "pomeranian", group: "Toy", description: "Inquisitive, bold, and lively. Poms are tiny but spirited dogs with a foxy face and a plush double coat.", avgLitterSize: "2–4", typicalPriceRange: "$1,500–$3,000", weight: "3–7 lbs", lifespan: "12–16 years", temperament: ["Inquisitive", "Bold", "Lively"] },
  { name: "Havanese", slug: "havanese", group: "Toy", description: "Outgoing, funny, and intelligent. The national dog of Cuba is a natural trick performer and devoted companion.", avgLitterSize: "3–5", typicalPriceRange: "$1,500–$3,000", weight: "7–13 lbs", lifespan: "14–16 years", temperament: ["Outgoing", "Funny", "Intelligent"] },
  { name: "Shetland Sheepdog", slug: "shetland-sheepdog", group: "Herding", description: "Playful, energetic, and bright. Shelties are small herding dogs known for their intelligence, loyalty, and beautiful coat.", avgLitterSize: "4–6", typicalPriceRange: "$1,000–$2,500", weight: "15–25 lbs", lifespan: "12–14 years", temperament: ["Playful", "Energetic", "Bright"] },
  { name: "Boston Terrier", slug: "boston-terrier", group: "Non-Sporting", description: "Friendly, bright, and amusing. The 'American Gentleman' is a compact, well-muscled dog with a tuxedo-like coat pattern.", avgLitterSize: "3–5", typicalPriceRange: "$1,000–$2,500", weight: "12–25 lbs", lifespan: "11–13 years", temperament: ["Friendly", "Bright", "Amusing"] },
  { name: "Maltese", slug: "maltese", group: "Toy", description: "Gentle, playful, and charming. Maltese are ancient toy dogs with flowing white coats and a sweet, devoted nature.", avgLitterSize: "3–5", typicalPriceRange: "$1,500–$3,000", weight: "4–7 lbs", lifespan: "12–15 years", temperament: ["Gentle", "Playful", "Charming"] },
  { name: "English Springer Spaniel", slug: "english-springer-spaniel", group: "Sporting", description: "Friendly, playful, and obedient. Springers are versatile sporting dogs equally at home in the field or the family room.", avgLitterSize: "5–7", typicalPriceRange: "$1,000–$2,000", weight: "40–50 lbs", lifespan: "12–14 years", temperament: ["Friendly", "Playful", "Obedient"] },
  { name: "Brittany", slug: "brittany", group: "Sporting", description: "Bright, fun-loving, and upbeat. Brittanys are energetic sporting dogs that excel in agility, obedience, and fieldwork.", avgLitterSize: "5–7", typicalPriceRange: "$1,000–$2,000", weight: "30–40 lbs", lifespan: "12–14 years", temperament: ["Bright", "Fun-Loving", "Upbeat"] },
  { name: "Cocker Spaniel", slug: "cocker-spaniel", group: "Sporting", description: "Gentle, smart, and happy. The smallest sporting spaniel is known for its merry disposition and beautiful, silky coat.", avgLitterSize: "4–6", typicalPriceRange: "$1,000–$2,500", weight: "20–30 lbs", lifespan: "10–14 years", temperament: ["Gentle", "Smart", "Happy"] },
  { name: "Border Collie", slug: "border-collie", group: "Herding", description: "Remarkably intelligent and athletic. Border Collies are the world's premier herding dogs and excel in agility and obedience competition.", avgLitterSize: "4–8", typicalPriceRange: "$1,000–$2,500", weight: "30–55 lbs", lifespan: "12–15 years", temperament: ["Intelligent", "Energetic", "Tenacious"] },
  { name: "Vizsla", slug: "vizsla", group: "Sporting", description: "Affectionate, gentle, and energetic. The Hungarian Vizsla is a versatile sporting dog often called the 'Velcro dog' for its attachment to owners.", avgLitterSize: "6–8", typicalPriceRange: "$1,500–$3,000", weight: "44–60 lbs", lifespan: "12–14 years", temperament: ["Affectionate", "Gentle", "Energetic"] },
  { name: "Pug", slug: "pug", group: "Toy", description: "Charming, mischievous, and loving. Pugs are small but sturdy companion dogs known for their wrinkled faces and big personalities.", avgLitterSize: "4–6", typicalPriceRange: "$1,000–$2,500", weight: "14–18 lbs", lifespan: "13–15 years", temperament: ["Charming", "Mischievous", "Loving"] },
  { name: "Weimaraner", slug: "weimaraner", group: "Sporting", description: "Friendly, fearless, and obedient. The sleek 'Gray Ghost' is a versatile sporting dog that loves to run and requires plenty of exercise.", avgLitterSize: "6–8", typicalPriceRange: "$1,500–$3,000", weight: "55–90 lbs", lifespan: "10–13 years", temperament: ["Friendly", "Fearless", "Obedient"] },
  { name: "Belgian Malinois", slug: "belgian-malinois", group: "Herding", description: "Confident, smart, and hardworking. Malinois are elite working dogs used by military and police forces around the world.", avgLitterSize: "6–10", typicalPriceRange: "$1,500–$3,500", weight: "40–80 lbs", lifespan: "14–16 years", temperament: ["Confident", "Smart", "Hardworking"] },
  { name: "Goldendoodle", slug: "goldendoodle", group: "Hybrid", description: "Friendly, intelligent, and low-shedding. This popular Golden Retriever–Poodle cross combines the best traits of both parent breeds.", avgLitterSize: "5–8", typicalPriceRange: "$2,000–$4,000", weight: "50–90 lbs", lifespan: "10–15 years", temperament: ["Friendly", "Intelligent", "Gentle"] },
  { name: "Rhodesian Ridgeback", slug: "rhodesian-ridgeback", group: "Hound", description: "Dignified, affectionate, and even-tempered. Originally bred to track lions, Ridgebacks are loyal family guardians.", avgLitterSize: "6–8", typicalPriceRange: "$2,000–$3,500", weight: "70–85 lbs", lifespan: "10–12 years", temperament: ["Dignified", "Affectionate", "Even-Tempered"] },
  { name: "West Highland White Terrier", slug: "west-highland-white-terrier", group: "Terrier", description: "Friendly, hardy, and entertaining. Westies are sturdy little terriers with bright white coats and confident personalities.", avgLitterSize: "3–5", typicalPriceRange: "$1,000–$2,500", weight: "15–20 lbs", lifespan: "13–15 years", temperament: ["Friendly", "Hardy", "Entertaining"] },
  { name: "Basset Hound", slug: "basset-hound", group: "Hound", description: "Charming, patient, and low-key. Basset Hounds are easygoing scent hounds with an exceptional nose and endearing droopy expression.", avgLitterSize: "6–8", typicalPriceRange: "$800–$1,500", weight: "40–65 lbs", lifespan: "12–13 years", temperament: ["Charming", "Patient", "Low-Key"] },
  { name: "Bichon Frise", slug: "bichon-frise", group: "Non-Sporting", description: "Playful, curious, and peppy. Bichons are cheerful little dogs with powder-puff white coats and a natural love of performing.", avgLitterSize: "3–5", typicalPriceRange: "$1,000–$2,500", weight: "12–18 lbs", lifespan: "14–15 years", temperament: ["Playful", "Curious", "Peppy"] },
  { name: "Akita", slug: "akita", group: "Working", description: "Courageous, dignified, and profoundly loyal. Akitas are powerful, independent dogs originally bred as guardians of Japanese royalty.", avgLitterSize: "5–7", typicalPriceRange: "$1,500–$3,500", weight: "70–130 lbs", lifespan: "10–13 years", temperament: ["Courageous", "Dignified", "Loyal"] },
  { name: "Newfoundland", slug: "newfoundland", group: "Working", description: "Sweet, patient, and devoted. Newfies are gentle giants renowned for their swimming ability and natural lifesaving instinct.", avgLitterSize: "6–8", typicalPriceRange: "$2,000–$3,500", weight: "100–150 lbs", lifespan: "9–10 years", temperament: ["Sweet", "Patient", "Devoted"] },
  { name: "Bloodhound", slug: "bloodhound", group: "Hound", description: "Friendly, independent, and inquisitive. Bloodhounds have the most powerful nose in the dog world and are prized for trailing ability.", avgLitterSize: "8–10", typicalPriceRange: "$1,500–$3,000", weight: "80–110 lbs", lifespan: "10–12 years", temperament: ["Friendly", "Independent", "Inquisitive"] },
  { name: "Saint Bernard", slug: "saint-bernard", group: "Working", description: "Playful, charming, and inquisitive. These gentle Alpine giants are famous rescue dogs with a calm, patient temperament.", avgLitterSize: "6–8", typicalPriceRange: "$1,500–$3,000", weight: "120–180 lbs", lifespan: "8–10 years", temperament: ["Playful", "Charming", "Inquisitive"] },
  { name: "English Cocker Spaniel", slug: "english-cocker-spaniel", group: "Sporting", description: "Energetic, merry, and responsive. English Cockers are compact sporting dogs with beautiful silky coats and a joyful disposition.", avgLitterSize: "5–7", typicalPriceRange: "$1,500–$2,500", weight: "26–34 lbs", lifespan: "12–14 years", temperament: ["Energetic", "Merry", "Responsive"] },
  { name: "Bull Terrier", slug: "bull-terrier", group: "Terrier", description: "Playful, charming, and mischievous. The egg-headed Bull Terrier is a robust, big-boned dog with a unique appearance and comic personality.", avgLitterSize: "4–5", typicalPriceRange: "$1,500–$3,000", weight: "50–70 lbs", lifespan: "12–13 years", temperament: ["Playful", "Charming", "Mischievous"] },
  { name: "Miniature American Shepherd", slug: "miniature-american-shepherd", group: "Herding", description: "Intelligent, versatile, and loyal. Mini Americans are compact herding dogs that share the Australian Shepherd's drive in a smaller package.", avgLitterSize: "5–7", typicalPriceRange: "$1,000–$2,500", weight: "20–40 lbs", lifespan: "12–13 years", temperament: ["Intelligent", "Versatile", "Loyal"] },
  { name: "Chesapeake Bay Retriever", slug: "chesapeake-bay-retriever", group: "Sporting", description: "Affectionate, bright, and sensitive. Chessies are powerful water retrievers bred to withstand the icy waters of the Chesapeake Bay.", avgLitterSize: "6–8", typicalPriceRange: "$1,500–$2,500", weight: "55–80 lbs", lifespan: "10–13 years", temperament: ["Affectionate", "Bright", "Sensitive"] },
  { name: "Soft Coated Wheaten Terrier", slug: "soft-coated-wheaten-terrier", group: "Terrier", description: "Happy, friendly, and deeply devoted. Wheatens are medium-sized terriers with a distinctive silky wheat-colored coat and exuberant personality.", avgLitterSize: "5–6", typicalPriceRange: "$1,500–$3,000", weight: "30–40 lbs", lifespan: "12–14 years", temperament: ["Happy", "Friendly", "Devoted"] },
  { name: "Italian Greyhound", slug: "italian-greyhound", group: "Toy", description: "Playful, alert, and sensitive. IGs are miniature sighthounds that combine the grace of a Greyhound with the gentleness of a lap dog.", avgLitterSize: "3–5", typicalPriceRange: "$1,500–$3,000", weight: "7–14 lbs", lifespan: "14–15 years", temperament: ["Playful", "Alert", "Sensitive"] },
];

export const US_STATES: Record<string, string> = {
  al: "Alabama", ak: "Alaska", az: "Arizona", ar: "Arkansas", ca: "California",
  co: "Colorado", ct: "Connecticut", de: "Delaware", fl: "Florida", ga: "Georgia",
  hi: "Hawaii", id: "Idaho", il: "Illinois", in: "Indiana", ia: "Iowa",
  ks: "Kansas", ky: "Kentucky", la: "Louisiana", me: "Maine", md: "Maryland",
  ma: "Massachusetts", mi: "Michigan", mn: "Minnesota", ms: "Mississippi",
  mo: "Missouri", mt: "Montana", ne: "Nebraska", nv: "Nevada", nh: "New Hampshire",
  nj: "New Jersey", nm: "New Mexico", ny: "New York", nc: "North Carolina",
  nd: "North Dakota", oh: "Ohio", ok: "Oklahoma", or: "Oregon", pa: "Pennsylvania",
  ri: "Rhode Island", sc: "South Carolina", sd: "South Dakota", tn: "Tennessee",
  tx: "Texas", ut: "Utah", vt: "Vermont", va: "Virginia", wa: "Washington",
  wv: "West Virginia", wi: "Wisconsin", wy: "Wyoming",
};

export function getBreedBySlug(slug: string): BreedInfo | undefined {
  return BREEDS.find((b) => b.slug === slug);
}
